package utils;

public interface Constants {
	
	String ONTOLOGY_A_NAME ="ONTOLOGY_A";
	String ONTOLOGY_B_NAME ="ONTOLOGY_B";
	
	String RECEIVE_A_SERVICE = "RECEIVE_A";
	String RECEIVE_B_SERVICE = "RECEIVE_B";
	String TRANSLATION_A_TO_B_SERVICE = "TRANSLATION_A_TO_B";
	String TRANSLATION_B_TO_A_SERVICE = "TRANSLATION_B_TO_A";

}
